@startuml erd

skinparam linetype ortho

entity Кандидат {
  Код_кандидата
  Ім'я
  Прізвище
  Номер_телефону
  Електронна_пошта
  Дата_народження
  Код_місцезнаходження
  Код_номер_паспорта
  Код_номер_водійського_посвідчення
  Код_вакансії
  Статус_працевлаштування
}

entity Вакансія {
  Код_вакансії
  Назва
  Код_компанії
  Заробітня_плата
  Код_категорії_вакансії
  Додаткова_інформація
}

entity Компанія {
  Код_компанії
  Назва
  Номер_телефону
  Код_місцезнаходження
  Код_виробничої_галузі
}

entity Категорія_вакансії {
  Код_категорії_вакансії
  Назва
}

entity Виробнича_галузь {
  Код_виробничної_галузі
  Назва
}

entity Місцезнаходження {
  Код_місцезнаходження
  Назва
}

Кандидат }o--o| Вакансія : Відгукується
Кандидат }o--|| Місцезнаходження
Вакансія }o--|| Компанія : Належить
Вакансія }o--|| Категорія_вакансії
Компанія }o--|| Виробнича_галузь
Компанія }o--|| Місцезнаходження

@enduml
